"""create_tables

Revision ID: b6a3585093d4
Revises: 
Create Date: 2025-04-18 14:29:57.931015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6a3585093d4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('category_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=False),
    sa.Column('birth_date', sa.DateTime(), nullable=False),
    sa.Column('sex', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('orders',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('order_date', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('status', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('priority', sa.Integer(), server_default='1', nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_table('products',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=False),
    sa.Column('length', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.category_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_table('order_items',
    sa.Column('order_item_id', sa.Integer(), nullable=False),
    sa.Column('products_count', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('order_item_id')
    )
    op.execute("""INSERT INTO users (user_name, birth_date, sex, email, password, is_admin) VALUES
               ('Елизавета', '2002-07-19', true, 'liza_vasenina@mail.ru', '$2b$12$hqedn.slDyoQcHdE8BKcdeJV7mC55mDbTXGA/vM4gaQGkJ/92g8vy', true)
               """)
    op.execute("""INSERT INTO categories (category_name) VALUES
               ('Климатическая техника'),
               ('Пылесосы'),
               ('Утюги и отпариватели'),
               ('Швейное оборудование'),
               ('Крупная бытовая техника'),
               ('Диваны и кресла'),
               ('Мебель для хранения'),
               ('Столы и стулья')
               """)
    op.execute("""INSERT INTO products(product_name, length, width, height, weight, price, stock, category_id) VALUES
               ('Кондиционер', 35, 78, 81, 32, 17300, 20, 1),
               ('Вентилятор', 44, 13, 125, 2.4, 2050, 40, 1),
               ('Радиатор', 14, 44, 64, 5.5, 2730, 30, 1),
               ('Увлажнитель воздуха', 37, 23, 23, 2, 4500, 45, 1),
               ('Сушилка для рук', 28, 27, 27, 2.5, 3200, 15, 1),
               ('Вертикальный пылесос', 64, 16, 17, 2.3, 4045, 15, 2),
               ('Робот-пылесос', 41, 36, 14, 2.5, 6000, 10, 2),
               ('Напольный пылесос', 49, 33, 27, 4.4, 5775, 35, 2),
               ('Отпариватель', 34, 16, 20, 1, 2600, 30, 3),
               ('Утюг', 30, 12, 15, 1.3, 1959, 50, 3),
               ('Швейная машинка', 40, 20, 33, 5, 6330, 10, 4),
               ('Стиральная машина', 61, 41, 85, 55, 22719, 30, 5),
               ('Посудомоечная машина', 67, 50, 87, 32, 19545, 15, 5),
               ('Холодильник', 65, 53, 174, 42, 22580, 50, 5),
               ('Кухонная плита', 70, 58, 96, 39, 35800, 25, 5),
               ('Диван', 195, 70, 50, 66, 16320, 10, 6),
               ('Кресло', 81, 90, 83, 45, 17600, 20, 6),
               ('Кресло-качалка', 77, 58, 31, 20, 13815, 5, 6),
               ('Пуфик', 40, 40, 15, 3.8, 2000, 7, 6),
               ('Кушетка', 202, 94, 30, 41, 32700, 6, 6),
               ('Шкаф', 24, 53, 12, 70, 8250, 25, 7),
               ('Комод', 81, 43, 15, 25, 2890, 10, 7),
               ('Стеллаж', 118, 38, 12, 21, 2200, 18, 7),
               ('Тумба', 52, 41, 16, 12.6, 1700, 20, 7),
               ('Стул', 68, 32, 47, 15, 4950, 40, 8),
               ('Стол', 82, 72, 10, 23, 2700, 27, 8),
               ('Табурет', 46, 41, 8, 2.7, 825, 30, 8)
               """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_items')
    op.drop_table('products')
    op.drop_table('orders')
    op.drop_table('users')
    op.drop_table('categories')
    # ### end Alembic commands ###
