services:
  app:
    container_name: shop_app
    build: .
    command: sh -c 'alembic upgrade head && cd app && uvicorn main:app --host 0.0.0.0 --port 8080'
    ports:
      - "8080:8080"
    env_file: ".env"
    networks:
      - fastapi-shop-network
    depends_on:
      db:
        condition: service_healthy
    restart: always

  db:
    image: postgres:17.4
    container_name: shop_db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    networks:
      - fastapi-shop-network

networks:
  fastapi-shop-network:
    driver: bridge

volumes:
  postgres_data: